// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEV8dkhkV2JsLnpc4HUbXTaggVGlw-er0',
    appId: '1:1094014287321:web:f99b3a7f5295e205f56dc8',
    messagingSenderId: '1094014287321',
    projectId: 'nnt-finance-d1773',
    authDomain: 'nnt-finance-d1773.firebaseapp.com',
    databaseURL: 'https://nnt-finance-d1773-default-rtdb.firebaseio.com',
    storageBucket: 'nnt-finance-d1773.appspot.com',
    measurementId: 'G-6Y9E9Q67X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7SwTxNUHV3CSTL_W5P5NWfVDZ4LANGQ',
    appId: '1:1094014287321:android:a02154d06bed326cf56dc8',
    messagingSenderId: '1094014287321',
    projectId: 'nnt-finance-d1773',
    databaseURL: 'https://nnt-finance-d1773-default-rtdb.firebaseio.com',
    storageBucket: 'nnt-finance-d1773.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGSA-rEZi4xdEyStOzFhmeLEwTYgKa4s',
    appId: '1:1094014287321:ios:36a2dc5d56b05e48f56dc8',
    messagingSenderId: '1094014287321',
    projectId: 'nnt-finance-d1773',
    databaseURL: 'https://nnt-finance-d1773-default-rtdb.firebaseio.com',
    storageBucket: 'nnt-finance-d1773.appspot.com',
    iosBundleId: 'com.example.collectionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXGSA-rEZi4xdEyStOzFhmeLEwTYgKa4s',
    appId: '1:1094014287321:ios:c67fd1a861192a1bf56dc8',
    messagingSenderId: '1094014287321',
    projectId: 'nnt-finance-d1773',
    databaseURL: 'https://nnt-finance-d1773-default-rtdb.firebaseio.com',
    storageBucket: 'nnt-finance-d1773.appspot.com',
    iosBundleId: 'com.example.collectionapp.RunnerTests',
  );
}
